### ISSUE TITLE
do not check in dll and exe files. use gitignore file to ignore files

### ISSUE THREAD

**Issue by kabirshakya** [NoelFajardo/PersonalExpenseTracker#1]
use gitignore to ignore files that should not be checked in . e.g. ignore everything under bin folder

**Comment by NoelFajardo** [comment]
.gitignore is implemented; folders bin/ obj/ packages/ or *.dll, *.exe will be ignored now.

**Comment by kabirshakya** [comment]
sloppy work. i see you haven’t removed all dll exe files... look carefully in detail

**Comment by NoelFajardo** [comment]
ref: https://git-scm.com/docs/gitignore
