### ISSUE TITLE
Filenames should be camel cased

### ISSUE THREAD

**Issue by kabirshakya** [NoelFajardo/PersonalExpenseTracker#5]
read about different casing styles. e.g. camel case, kebab case and so on...

in .net we usually camel case so
BalExpense not balExpense
and so on...

**Comment by NoelFajardo** [comment]
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions

I will use Pascal casing style for most of the naming and camel casing for parameters from now on.

**Comment by kabirshakya** [comment]
is this done? if you don't comment "done" i don't know if it's done or you still working on it

**Comment by NoelFajardo** [comment]
done
