### ISSUE TITLE
add a logging framework to log your messages

### ISSUE THREAD

**Issue by kabirshakya** [NoelFajardo/PersonalExpenseTracker#6]
you can either review which logging framework your company is using 

or

i recommend looking into NLog framework for logging
and catch errors properly

e.g.
catch (Exception e)
{
 throw;
}
this is really useless
if you catch an exception, you should handle it . at the very least log it to a file or something so we know it errored.

i recommend reading about proper ways to handle exceptions.

**Comment by NoelFajardo** [comment]
BAL, DAL and Model classs used only throw but it will return to UI where I am handling it will display the message.. But, u are right it's better to have a log to handle here in logic layers class method.

**Comment by NoelFajardo** [comment]
will read about Nlog or other framework and will implement it.

**Comment by kabirshakya** [comment]
> BAL, DAL and Model classs used only throw but it will return to UI where I am handling it will display the message.. But, u are right it's better to have a log to handle here in logic layers class method. 

it is redundant to catch an exception and type "throw"... by default, it will throw the exception to the caller.
try it. 
remove that try catch and your UI will still get the exception

**Comment by NoelFajardo** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-catch. 

Ok got it!...  DONE

**Comment by kabirshakya** [comment]
closing this for now. but i see you took the easy route that is removing try catch blocks. Think of it this way - you are developing backend system and someone else is writing the UI. So, when you are doing backend development, it is your responsibility to catch errors and send it to the UI developers so they can display it accordingly. It is not UI developers responsibility to parse out what exception xyz may mean and show user friendly message. Makes sense? But, that is more of a validation/exception handling task so closing this one for now.
